name: .NET Build
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install dependencies
      run: msbuild -t:restore
    - name: Build project
      run: msbuild LegacyInstaller/LegacyInstaller.csproj /t:Build /p:Configuration=Release
    - name: Cleanup release
      shell: bash
      run: |
        find "LegacyInstaller/bin/Release" -type f ! \( -name "*.exe" -o -name "*.dll" \) -delete
        cp "LICENSE" "LegacyInstaller/bin/Release/LICENSE.LegacyInstaller.txt" || :
    - name: Upload Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: LegacyInstaller-${{ github.sha }}
        path: ./LegacyInstaller/bin/Release/
    - name: Extract Release Version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      shell: bash
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    - name: Zip for Release
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      working-directory: ./LegacyInstaller/bin/Release
      run: zip LegacyInstaller.zip -r .
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: LegacyInstaller v${{ steps.get_version.outputs.version }}
        files: ./LegacyInstaller/bin/Release/LegacyInstaller.zip
